### ISSUE TITLE
feat: Black formatting for pushes and pull requests

### ISSUE THREAD

**Issue by DivineBicycle** [GradienceTeam/Gradience#303]
### Feature description

Using the black GitHub action:
```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
```

This would make sure all code style is the same no matter who contributes it.

### Additional Context

[Here's](https://black.readthedocs.io/en/stable/integrations/github_actions.html) some more information about the template

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).
